### PR TITLE
Split generic-seeming functionality into their own files

### PR DESCRIPTION
**Pull request by OshinKaramian**
## Description
This is in response to @mjneil's comment in https://github.com/videojs/videojs-contrib-hls/pull/1212#issuecomment-318758797.  

This is really just reorganizing to pull some of the more common/generic functionality from master-playlists-controller.js out into their own files.  I'm sure more can be pulled from other files as well (I haven't dug deep enough to know).

No logic changes, just shuffling some functions around.

## Specific Changes proposed
Please list the specific changes involved in this pull request.

## Requirements Checklist
- [x] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [x] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](http://jsbin.com/liwecukasi/edit?html,output))
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Comment by mjneil** [comment]
Does the codec test get run properly with `npm run test`? i think `util/codecs.js` needs `util/codecs.test.js`

**Comment by OshinKaramian** [comment]
Whoops, I didn't realize that that's how tests were run (I assumed it was picking out anything with Qunit in the test folder and running it).  Should be resolved on the latest commit.

**Comment by mjneil** [comment]
would it make sense to move the `bin-utils.js` file to `util/bin.js`?

**Comment by OshinKaramian** [comment]
Closing this, as it will cause conflicts when moving to videojs/http-streaming.  Refactor PRs should probably go in there as this project is deprecated in favor of videojs/http-streaming.

**Comment by OshinKaramian** [comment]
Reference: https://github.com/videojs/http-streaming/pull/17 for similar changes.

**Pull request closed without merging**
