### PR TITLE
Validate existence of h264Frame where needed

### PR DESCRIPTION
**Pull request by ntadej**
Sometimes HLS crashes due to not existing h264Frame. Validate it before writing data to it and it plays/works properly afterwards.

### CODE REVIEW

**Comment by dmlap** [comment]
@ntadej thanks for the PR! I think in this case that something is going wrong at another point in the parsing process that we should probably get to the bottom of. Do you have a reduced test case available that causes this to occur?

**Comment by ntadej** [comment]
Our streams do not start properly with your HLS implementation do to missing ADTS headers at the beginning. This may cause the issues, but our streams play completely fine on iOS, Android and other devices.

We are preparing a test stream for you (I plan to open another bug, as there are some problems with quality switching and general playback after 0.11.1 -> 0.11.2 update). Is there a preferred email to send the URL to you, as we can't make it public at the moment?

**Comment by dmlap** [comment]
@ntadej email me at dlapalomento at brightcove dot com.

**Comment by ntadej** [comment]
I've sent you the url on email and opened #236. Note that playback on 0.11.2 works again after updating to Video.js 4.12.5 but quality switching still has problems as described in #236.

**Comment by ntadej** [comment]
We investigated why this is necessary and found out that H264 data is not aligned inside the TS packet. It seems to be a valid case to have this `h264Frame` validation and data before first frame can be ignored.

**Comment by forbesjo** [comment]
We think this is fixed with HLS 1.0, could you test this in the development branch?

**Pull request closed without merging**
