### PR TITLE
Feature: Alternate renditons for video tracks

### PR DESCRIPTION
**Pull request by tchakabam**
## Description

Adds support for alternate renditions video tracks.

Test streams can be provided.

## Specific Changes proposed

Analoguous implementation to alternate audio renditions and text tracks.

## Requirements Checklist
- [x] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](http://jsbin.com/liwecukasi/edit?html,output))
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Comment by tchakabam** [comment]
Hey, we have done a pretty massive fork of the HLS lib in our product and had to advance quite rapidly.

Now we'd like to contribute back a lot of the features and improvements into upstream in order to keep in touch with the project here :)

One of the features is alternate renditions for video which we are actively using.

This is pretty much how we implemented this in our fork. The only problem here currently is making work adaptive bitrates across alternate renditions correctly. It seems that in the implementation proposed 

Another issue we see is that the player always chooses the default track first. We have built-in an option to have the player pre-load another track based on it's ID. Wouldn't this be something useful anyhow? Because video tracks have a higher switching effort than audio tracks obviously.

Another thing is that we have added an option to disable audio downloading (when delivered in a seperate track), as we may want to deliver playlists that contain audio but don't want to actually play or download it (it's an optimization for our use-case). Turns out disabling audio streaming was quite easy, but I may deliver this a seperate PR.

We added an API on the HLS client to easily handle track switching for video (which could be extended to other tracks) as you can see in the PR.

**Comment by tchakabam** [comment]
@BrandonOCasey it seems odd all tests are broken suddenly, i didn't add any. will check this out. do you have any idea what could be the reason?

**Comment by tchakabam** [comment]
@BrandonOCasey @imbcmdth hey guys, i am reaching out to you as being some of the active core contributors here. 

This is about adding this as a feature, which would allow having multiple video tracks (renditions not qualities!).

This is for multi-view applications where we live-stream from multiple cameras. So it is a really top-notch thing we think. 

So there are for example 4 cameras, so 4 video renditions, and each renditions has multiple quality levels, just as we know it, but times 4 :)

We are doing this with Wowza, which supports it, and it is also allowed by the HLS spec. So we think that this lib should support it, we hope you guys will collaborate to bring into the upstream branch so we dont need to do our stuff in a fork anymore :)

I will set up some test content if you are interested. We probably should have some also for the test suite, which needs to be updated here obviously.

For better understanding, a playlist may look like this:

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="en",NAME="English",DEFAULT=YES,URI="chunklist_b192000_ao_slen_t64RW5nbGlzaA==.m3u8"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="mobile",NAME="Camera 1",DEFAULT=YES,URI="chunklist_b500000_t64Q2FtZXJhIDE=.m3u8"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="mobile",NAME="Camera 2",DEFAULT=NO,URI="chunklist_b500000_t64Q2FtZXJhIDI=.m3u8"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="mobile",NAME="Camera 3",DEFAULT=NO,URI="chunklist_b500000_t64Q2FtZXJhIDM=.m3u8"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="mobile",NAME="Camera 4",DEFAULT=NO,URI="chunklist_b500000_t64Q2FtZXJhIDQ=.m3u8"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="low",NAME="Camera 1",DEFAULT=YES,URI="chunklist_b500000_t64Q2FtZXJhIDE=.m3u8"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="low",NAME="Camera 2",DEFAULT=NO,URI="chunklist_b1000000_t64Q2FtZXJhIDI=.m3u8"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="low",NAME="Camera 3",DEFAULT=NO,URI="chunklist_b1000000_t64Q2FtZXJhIDM=.m3u8"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="low",NAME="Camera 4",DEFAULT=NO,URI="chunklist_b1000000_t64Q2FtZXJhIDQ=.m3u8"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="medium",NAME="Camera 1",DEFAULT=YES,URI="chunklist_b2000000_t64Q2FtZXJhIDE=.m3u8"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="medium",NAME="Camera 2",DEFAULT=NO,URI="chunklist_b2000000_t64Q2FtZXJhIDI=.m3u8"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="medium",NAME="Camera 3",DEFAULT=NO,URI="chunklist_b2000000_t64Q2FtZXJhIDM=.m3u8"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="medium",NAME="Camera 4",DEFAULT=NO,URI="chunklist_b2000000_t64Q2FtZXJhIDQ=.m3u8"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="high",NAME="Camera 1",DEFAULT=YES,URI="chunklist_b4000000_t64Q2FtZXJhIDE=.m3u8"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="high",NAME="Camera 2",DEFAULT=NO,URI="chunklist_b4000000_t64Q2FtZXJhIDI=.m3u8"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="high",NAME="Camera 3",DEFAULT=NO,URI="chunklist_b4000000_t64Q2FtZXJhIDM=.m3u8"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="high",NAME="Camera 4",DEFAULT=NO,URI="chunklist_b4000000_t64Q2FtZXJhIDQ=.m3u8"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="hd",NAME="Camera 1",DEFAULT=YES,URI="chunklist_b7500000_t64Q2FtZXJhIDE=.m3u8"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="hd",NAME="Camera 2",DEFAULT=NO,URI="chunklist_b7500000_t64Q2FtZXJhIDI=.m3u8"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="hd",NAME="Camera 3",DEFAULT=NO,URI="chunklist_b7500000_t64Q2FtZXJhIDM=.m3u8"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="hd",NAME="Camera 4",DEFAULT=NO,URI="chunklist_b7500000_t64Q2FtZXJhIDQ=.m3u8"
#EXT-X-STREAM-INF:BANDWIDTH=500000,NAME="Camera 1",CODECS="avc1.66.30,mp4a.40.2",RESOLUTION=512x288,AUDIO="aac",VIDEO="mobile"
chunklist_b500000_t64Q2FtZXJhIDE=.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1000000,NAME="Camera 1",CODECS="avc1.77.32,mp4a.40.2",RESOLUTION=640x360,AUDIO="aac",VIDEO="low"
chunklist_b1000000_t64Q2FtZXJhIDE=.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2000000,NAME="Camera 1",CODECS="avc1.77.41,mp4a.40.2",RESOLUTION=848x480,AUDIO="aac",VIDEO="medium"
chunklist_b2000000_t64Q2FtZXJhIDE=.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=4000000,NAME="Camera 1",CODECS="avc1.100.41,mp4a.40.2",RESOLUTION=1280x720,AUDIO="aac",VIDEO="high"
chunklist_b4000000_t64Q2FtZXJhIDE=.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=7500000,NAME="Camera 1",CODECS="avc1.100.40,mp4a.40.2",RESOLUTION=1920x1080,AUDIO="aac",VIDEO="hd"
chunklist_b7500000_t64Q2FtZXJhIDE=.m3u8
```

**Comment by gesinger** [comment]
Hey @tchakabam , thanks for the awesome PR, we definitely should have support for multiple video tracks. As a start, I saw you mentioned that you are setting up some test content. We'd definitely like to give it a shot and see it in action.

**Comment by tchakabam** [comment]
@gesinger Hey thank you very much for your answer! We would really love to continue using the Videojs HLS library as it proved to support well a couple of things we needed, and adding the Alternate Video feature was easy enough :) So would be great to get this in so we can keep the benefits on all sides.

We are currently setting up some test content (we can not share the content of our direct customers).

We are going to put this on a spoofed CDN name and then we can share it here :)

**Comment by tchakabam** [comment]
@gesinger 

Here is the test content. I have made a commit which replaces the test URL 
 (we will revert that later). with our multi-video-track test stream, which you find here: http://13.81.114.0:1935/vod/smil:playlist.smil/playlist.m3u8

That should make it very easy for you to test, just git-checkout this branch head.

Then you may use the `player` object in `window` like this to switch tracks from console:

```
player.hls.enableVideoTrack(0..2)
```

and

```
player.hls.enableAudioTrack(0..2)
```

With the respective track index you want. Each video track has 3 quality variants :) Any combination is possible (just like for audio and text).

This content is Bigbuckbunny, TOS and Sintel on one stream (cropped to the length of BBB).

There are also the three respective audio tracks of course.

Let us know how this works for you. We think it's a pretty promising feature.

Remaining TODOs may be:

* Figure out if automatic and manual ABR switching will still work in all cases (it should not jump back to the initial video track..).

* We need an options parameter to set the initial video track to start with. We also think this should exists for audio. As the bandwidth overhead of loading the "wrong" one is high and can double join time.

* We need to write some tests obviously.

The resulting M3u8 looks like this:

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="en1",NAME="English Big Buck Bunny",DEFAULT=YES,URI="chunklist_w991032164_b192000_ao_slen1_t64RW5nbGlzaCBCaWcgQnVjayBCdW5ueQ==.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="en2",NAME="English Sintel",DEFAULT=NO,URI="chunklist_w991032164_b192000_ao_slen2_t64RW5nbGlzaCBTaW50ZWw=.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="en3",NAME="English Tears of Steal",DEFAULT=NO,URI="chunklist_w991032164_b192000_ao_slen3_t64RW5nbGlzaCBUZWFycyBvZiBTdGVhbA==.m3u8"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="low",NAME="Big Buck Bunny",DEFAULT=YES,URI="chunklist_w991032164_b1500000_t64QmlnIEJ1Y2sgQnVubnk=.m3u8"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="low",NAME="Sintel",DEFAULT=NO,URI="chunklist_w991032164_b1500000_t64U2ludGVs.m3u8"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="low",NAME="Tears of Steal",DEFAULT=NO,URI="chunklist_w991032164_b1500000_t64VGVhcnMgb2YgU3RlYWw=.m3u8"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="high",NAME="Big Buck Bunny",DEFAULT=NO,URI="chunklist_w991032164_b3000000_t64QmlnIEJ1Y2sgQnVubnk=.m3u8"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="high",NAME="Sintel",DEFAULT=NO,URI="chunklist_w991032164_b3000000_t64U2ludGVs.m3u8"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="high",NAME="Tears of Steal",DEFAULT=NO,URI="chunklist_w991032164_b3000000_t64VGVhcnMgb2YgU3RlYWw=.m3u8"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="hd",NAME="Big Buck Bunny",DEFAULT=NO,URI="chunklist_w991032164_b5000000_t64QmlnIEJ1Y2sgQnVubnk=.m3u8"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="hd",NAME="Sintel",DEFAULT=NO,URI="chunklist_w991032164_b5000000_t64U2ludGVs.m3u8"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="hd",NAME="Tears of Steal",DEFAULT=NO,URI="chunklist_w991032164_b5000000_t64VGVhcnMgb2YgU3RlYWw=.m3u8"
#EXT-X-STREAM-INF:BANDWIDTH=1500000,NAME="Big Buck Bunny",CODECS="avc1.100.40,mp4a.40.2",RESOLUTION=640x360,AUDIO="aac",VIDEO="low"
chunklist_w991032164_b1500000_t64QmlnIEJ1Y2sgQnVubnk=.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3000000,NAME="Big Buck Bunny",CODECS="avc1.100.40,mp4a.40.2",RESOLUTION=1280x720,AUDIO="aac",VIDEO="high"
chunklist_w991032164_b3000000_t64QmlnIEJ1Y2sgQnVubnk=.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=5000000,NAME="Big Buck Bunny",CODECS="avc1.100.40,mp4a.40.2",RESOLUTION=1920x1080,AUDIO="aac",VIDEO="hd"
chunklist_w991032164_b5000000_t64QmlnIEJ1Y2sgQnVubnk=.m3u8
```

**Comment by tchakabam** [comment]
@gesinger Concerning the multiple audio tracks, there seems to be a problem with the 2nd and 3rd.

We'll look at fixing that. Because of course we need to make sure there is no regression on the audio-track switching feature coming with this. Meanwhile, we can also test with content that has multiple audio tracks still to see if that still works :)

**Comment by jmeintjes** [comment]
Hey everyone... Just curious to know whether there's a plan to have this in a release soon?

**Comment by enzanki-ars** [comment]
Sorry that I did not realize that this pull request existed.  My searching failed me as I only searched for the technical term.  

I have been thinking about this for a while now, and I think that video.js should add video tracks there first before here allowing people to use video tracks anywhere and not just with HLS streams.  Once that is added, that might allow this project to add video tracks in a more consistent manor.

**Comment by forbesjo** [comment]
Thank you for your PR but we will not be accepting new changes for this repo and will be [archived](https://help.github.com/articles/about-archiving-repositories/) very soon. I would advise you to open your PR against the next iteration of this project at https://github.com/videojs/http-streaming.

**Pull request closed without merging**
