### PR TITLE
Always write out metadata at the start of segments and refactor of h264stream

### PR DESCRIPTION
**Pull request by gkatsev**
In some cases (most likely badly encoded video), segments didn't start
with a keyframe so they ended up getting squished because flash didn't
know how to play them.

### CODE REVIEW

**Comment by dmlap** [comment]
@gkatsev is there an easy way to test this?

**Comment by gkatsev** [comment]
Not sure. I have a stream that shows this issue currently.
Working on the failing test currently as well.

**Comment by gkatsev** [comment]
Looks like the current test is failing because it is entering into this section, so, might be able to duplicate the currently failing test into a working test for this option.

**Comment by gkatsev** [comment]
I have an update to fix the currently broken test. I don't currently have a test that checks the functionality in this PR because it's impossible to stub out the methods that we care about, currently.

**Pull request merged**
