### PR TITLE
Move metadata to hidden folder

### PR DESCRIPTION
**Pull request by piotr-cz**
## Description

Move metadata to hidden folder and update references

This is an adequate PR to https://github.com/videojs/video.js/pull/3627

## Specific Changes proposed

This moves files

- ISSUE_TEMPLATE.md
- PULL_REQUEST_TEMPLATE.md

to own `.github` folder

Reference: GitHub help > [Helping people contribute to your project
](https://help.github.com/articles/helping-people-contribute-to-your-project/)

## Requirements Checklist
- [ ] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](http://jsbin.com/liwecukasi/edit?html,output))
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Comment by gesinger** [comment]
Looks like a small typo in the directory they are being moved to (,git instead of .github):

ISSUE_TEMPLATE.md → ,git/ISSUE_TEMPLATE.md
PULL_REQUEST_TEMPLATE.md → ,git/PULL_REQUEST_TEMPLATE.md

**Comment by piotr-cz** [comment]
Thank you that was a bad typo. It's fixed now.

**Comment by gesinger** [comment]
Thanks @piotr-cz , LGTM

**Comment by dmlap** [comment]
Looks good. Thanks @piotr-cz!

**Pull request merged**
