### PR TITLE
fixed bug :  if m3u8 link is a redirect url ,it's not working

### PR DESCRIPTION
**Pull request by YouYII**
I use this link : http://zy160325.podbean.org/hls/web/d6gidx/2.mp4,
It works on Safari  and  [hlsjs](https://github.com/dailymotion/hls.js) , 
But it does not work on this project , 
I fixed this problem.

### CODE REVIEW

**Comment by samward1985** [comment]
Ha! It looks like we were doing this at the exact same time, and came up with the same solution: https://github.com/videojs/videojs-contrib-hls/pull/647

:D

**Comment by dmlap** [comment]
Mentioned it in #647 but IE doesn't support `responseURL`

**Comment by forbesjo** [comment]
Could you add a check for responseURL to handle IE?

**Comment by dmlap** [comment]
We're trying to support IE and (as written) this PR wouldn't work because of its use of responseURL. If you have another approach to solve this problem, don't hesitate to re-open this!

**Pull request closed without merging**
