### PR TITLE
Just upload source files to npm

### PR DESCRIPTION
**Pull request by forbesjo**
This PR is to reduce the amount of files there are on npm.

### CODE REVIEW

**Comment by gkatsev** [comment]
This will break everyone using contrib-hls. Those that include it via browserify will break because the es5 folder is missing. Those that include it via the dist folder would break because that folder is missing.

**Comment by gkatsev** [comment]
Oh, too much read obscured things, while it should work, I think it's nicer to have all the files included in npm.

**Comment by gkatsev** [comment]
removing `dist-test` sounds fine. I think keeping the rest would be good.

**Comment by forbesjo** [comment]
I'll just remove `dist-test` and `utils` (20mb) in this PR.

**Pull request merged**
