### PR TITLE
run browserify-shim transform on watch:js:browserify

### PR DESCRIPTION
**Pull request by BrandonOCasey**

### CODE REVIEW

**Comment by gkatsev** [comment]
Must've missed that one in https://github.com/videojs/videojs-contrib-hls/pull/675
can you double check and make sure that's the only one left over?

**Comment by BrandonOCasey** [comment]
will do

**Comment by BrandonOCasey** [comment]
@gkatsev seems like the only one that was missed was the one for `watch:js:browserify`

**Comment by gkatsev** [comment]
LGTM

**Pull request merged**
