### PR TITLE
Synchronize timestamp offsets between h.264 and AAC streams

### PR DESCRIPTION
**Pull request by ronhopper**
Solves Issue https://github.com/videojs/videojs-contrib-hls/issues/211

When the audio and video streams start at slightly different times, the existing code captures different PTS offsets. This causes an audio lag problem during playback.

In this pull request, rather than capturing the PTS offset independently in the AAC and h.264 streams, the first stream within the TS segment initializes the offset for both streams, which is then set via the new function `setTimeStampOffset`. This is clearer than using self-modifying functions within each stream independently and synchronizes audio/video streams that do not share the same absolute starting time.

### CODE REVIEW

**Comment by ntadej** [comment]
This fixes audio-video sync with our streams without any noticeable regressions.

**Comment by heff** [comment]
@szatmary, any chance we could get you to take a quick look at this and verify that it's a safe change?

**Comment by szatmary** [comment]
I see nothing obviously wrong

**Comment by dmlap** [comment]
Merged via d94275ef8cf27ae6d227d20ccb9abb9e9cb499ae

**Pull request closed without merging**
