### PR TITLE
Fix for #550 and #555

### PR DESCRIPTION
**Pull request by svenspielvogel**
this is a fix that resolves the wowza and the ended bug. Maybe there is a better solution, but it works fine.

### CODE REVIEW

**Comment by dmlap** [comment]
Thanks for sharing your patch! It looks like there's a couple different tweaks going on in there. Would you mind explaining the extra behaviors you added in and the scenarios where they're helpful?

**Comment by svenspielvogel** [comment]
Hey David. The problem is, that in some cases, especially when the video itself might be missing some audio frames the Wowza tends to pass the streams damaged as they are. This might lead to a gap between segments. What does that mean? Let's say Segment 1 Ends at Timestamp 5.300 - then it might happen, that the next segments starts at 5.350. This results in two timerange object. Or, what i discovered yesterday to even more TimeRanges. 
1. Problem: Video stops playing since there is a gap
Solve: if next timerange isnt far away (<0.5secs) jump over gap
2. Problem: Video loads segments in a loop: e.g. media_0.ts >> media_0.ts and so on.
Solve: Find real buffered end and get media index - my approach might still lead to a loop if we have 3 time ranges, but are still playing in the first time range. I'm gonna fix this pretty soon. I've to iterate through all timeranges. another solution, maybe the better one would be not to create a second timerange. Actually I wasn't able to figure it out in that short time I had, so this might be a good way. Any ideas on that?
3. The Plug-In doesn't always throw correct errors. e.g. loosing network or poor network (GPRS 64kBit/s)
Solve: setting up a retry count and throw error if it occurs.

**Comment by svenspielvogel** [comment]
Another this. Travis fails. But this is because of 9d075a3. At this commit i set up my own 404 handling. Because the plugin throws an instant error even if enough buffer is present.
Just imagine followin use case: You sit in a Metro and at Station 1 you have 4G so you are buffering. Then you drive further and suddenly network falls away. Then, just 5 seconds later you get 4G again.

What happens at the old build and the current Tests: Even with 30 seconds in Buffer a miss on loading a segments leads to a error.
My Approach lets you still play the stream as log as you have buffer. (I love this behavior from the Amazon Instant Video Player). And as soon as you have Network the same segment gets buffered. After stalling too long, i will still throw a error 2.

**Comment by nickygerritsen** [comment]
We seem to also have this issue, but (manually) applying the patch did not really solve it... 

I do get the following console errors after a short while:

```
VIDEOJS: WARN: Problem encountered with the current HLS playlist. No suitable alternatives found.
video.js:19152 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. MediaError {code: 4, message: "The media could not be loaded, either because the …rk failed or because the format is not supported."}_logType @ video.js:19152log.error @ video.js:19103error @ video.js:11654handleTechError_ @ video.js:10459ret @ video.js:18981ret @ video.js:18981data.dispatcher @ video.js:18629
video.js:19152 VIDEOJS: WARN: Problem encountered with the current HLS playlist. No suitable alternatives found.
video.js:19152 VIDEOJS: WARN: Problem encountered with the current HLS playlist. No suitable alternatives found.
17transmuxer-worker.js:49 Uncaught InvalidStateError: Failed to set the 'duration' property on 'MediaSource': The MediaSource's readyState is not 'open'.
```

Which I didn't get before.

**Comment by svenspielvogel** [comment]
Can you provide the Video. I'd like to have a look into it. @nickygerritsen

**Comment by nickygerritsen** [comment]
No problem, it is: http://hls.streamonecloud.net/livestream/amlst:h3kXcf2yyam/playlist.m3u8

**Comment by cdhowie** [comment]
v2.0.0 seems to fix the "ended" issue for me (#555).  I'm not sure why, but it does.

**Comment by cdhowie** [comment]
I take it back; there are still some videos where the ended event doesn't fire, even with v2.0.0.

**Comment by forbesjo** [comment]
We've added a lot of fixes related to gaps, is this still an issue when using the latest version?

**Comment by TylerZubke** [comment]
This is still happening for me. See #834. 
I tried @svenspielvogel fixes and the stream freezes with no error or anything indicating what happened. It also seems to happen more frequently than what occurs in my issue.

**Comment by gesinger** [comment]
Thanks again for the PR @svenspielvogel . As to your comments above regarding what this fixes, we actually have made a lot of changes around those very areas (since we found them problematic as well). In order:

```
Problem: Video stops playing since there is a gap
Solve: if next timerange isnt far away (<0.5secs) jump over gap
```
We do a few different things now. In mux.js, we will fill some audio gaps with silent frames ( https://github.com/videojs/mux.js/pull/130 and https://github.com/videojs/mux.js/pull/143 ). In videojs-contrib-hls, we have https://github.com/videojs/videojs-contrib-hls/blob/master/src/playback-watcher.js which will skip over gaps in known error conditions.

```
Problem: Video loads segments in a loop: e.g. media_0.ts >> media_0.ts and so on.
Solve: Find real buffered end and get media index - my approach might still lead to a loop if we have 3 time ranges, but are still playing in the first time range. I'm gonna fix this pretty soon. I've to iterate through all timeranges. another solution, maybe the better one would be not to create a second timerange. Actually I wasn't able to figure it out in that short time I had, so this might be a good way. Any ideas on that?
```
We now have much better fetching behavior, and it has been resilient against looping segment requests. Please give it a shot and let us know if you see otherwise!

```
The Plug-In doesn't always throw correct errors. e.g. loosing network or poor network (GPRS 64kBit/s)
Solve: setting up a retry count and throw error if it occurs.
```
We've been working on better error reporting/events, and now will retry the last stream if it fails https://github.com/videojs/videojs-contrib-hls/pull/1039 .

As for the case @TylerZubke posted, it looks like that was solved.

Thanks again for the PR, and please let us know if you're still experiencing issues with the latest version of videojs-contrib-hls (as of this comment, v5.5.0). Thank you.

**Pull request closed without merging**
