### PR TITLE
fix: SegmentLoader.handleUpdateEnd_ run after player was disposed

### PR DESCRIPTION
**Pull request by andrewmnlv**

### CODE REVIEW

**Comment by dmlap** [comment]
Thanks for the PR! It seems to me though that we should have unregistered the handleUpdateEnd_ listener after dispose() so this shouldn't have been invoked in the first place. Would you be up for modifying this PR to properly clean up the listener on dispose instead?

**Comment by andrewmnlv** [comment]
@dmlap np, on weekend

**Comment by andrewmnlv** [comment]
@dmlap up

**Comment by dmlap** [comment]
Perfect, thanks!

**Pull request merged**
