### PR TITLE
add bundle-collapser to save 5.5kb (3% size reduction)

### PR DESCRIPTION
**Pull request by BrandonOCasey**
## Description
add bundle-collapser as a plugin to save 5.5kb in the minified file

## Requirements Checklist
- [x] Feature implemented / Bug fixed
- [x] Reviewed by Two Core Contributors

### CODE REVIEW

**Comment by BrandonOCasey** [comment]
not sure why a test is failing, doesn't seem related to anything I did...

**Comment by dmlap** [comment]
Should be fixed in master now. Rerunning Travis.

**Comment by dmlap** [comment]
LGTM

**Comment by forbesjo** [comment]
LGTM

**Pull request merged**
